#!/bin/bash

cd specifications || exit

java -jar "../tools/antlr/antlr-4.11.1-complete.jar" -no-listener -package compiler.parser -o ../src/main/java/compiler/parser Grammar.g4

cd ..
rm -f src/main/java/compiler/parser/*.tokens
rm -f src/main/java/compiler/parser/*.interp
