#!/bin/bash
chmod +x antlr

INPUT_FILE=${1:-input.e}

./antlr
javac -cp "tools/antlr/antlr-4.11.1-complete.jar" -d bin $(find src -name "*.java")
java -cp "bin:tools/antlr/antlr-4.11.1-complete.jar" main.Main "$INPUT_FILE"
